Add library building of packages and included small helper-functions
ipa320/ipa_coverage_planning pull request #5
Opened 2019-11-26 08:09 UTC by ipa-foj

2019-11-26 08:14 UTC, ipa-rmb requested changes

2019-11-26 08:14 UTC, ipa-rmb commented on ipa_building_navigation/CMakeLists.txt
> +set(ROS_BUILD_TYPE Debug)
Why in debug? Shouldn'd it build faster release code?

2019-11-26 08:14 UTC, ipa-rmb commented on ipa_building_navigation/common/src/genetic_TSP.cpp
> +		int changeing_counter = const_generations_number_; //this variable is a counter for how many times a path has been the same
changing (Rechtschreibung :-D)

2019-11-27 11:00 UTC, ipa-rmb requested changes
Travis is not building, please check. Furthermore, please harmonize the introduced spaces in the CMakeLists.txt files to tabs, I guess the remainder is all tabs.

2020-02-28 08:40 UTC, ipa-mtb commented
Problem seems to be position independent code in ``libdlib`` in ``cob_extern``.
Might want to try out using this branch (https://github.com/ipa-mtb/cob_extern/tree/feature/fpic_dlib), if this would make travis happy

2020-09-22 12:24 UTC, closed without merging